### ISSUE TITLE
Can't find variable: fetch

### ISSUE THREAD

**Issue by JeongJun-Lee** [0nza1101/ionic3-leaflet-mbtiles#3]
Hello, really thank you for your offline map support.

It works well at browser but when I built this source for iPhone Simulator and ran on iOS 10.2.
As soon as the App starts, it'll meet the error and cannot proceed more.

![image](https://user-images.githubusercontent.com/11474775/34510387-4e53d44e-f075-11e7-9cbc-0b89224bfacf.png)

**Comment by 0nza1101** [comment]
Hello,
As I told you on the previous issue I updated the repo, this should be fixed now, Its working for me(iPhone Simulator iOS 11.1) it should be caused by the iOS version you use you should use the polyfills that I put inside `main.ts` to make it compatible with old iOS version.
<img width="326" alt="screen shot 2018-01-06 at 23 50 40" src="https://user-images.githubusercontent.com/13056641/34644747-c5864a32-f33c-11e7-8608-ea4565c12952.png">

**Comment by JeongJun-Lee** [comment]
it was fixed with new repo
